# Generated by GitHub Copilot
"""Reusable services for the UdaPlay gaming research project."""

from __future__ import annotations

import json
import os
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, List, Optional, TypedDict

from dotenv import load_dotenv
from pydantic import BaseModel, Field
from tavily import TavilyClient

from lib.agents import Agent
from lib.documents import Document
from lib.memory import LongTermMemory, MemoryFragment
from lib.tooling import Tool, tool
from lib.vector_db import VectorStore, VectorStoreManager


CURRENT_INFO_PATTERN = re.compile(
    r"\b(current|currently|today|latest|recent|recently|now|right now|working on|upcoming)\b",
    re.IGNORECASE,
)
DEVELOPER_PATTERN = re.compile(r"\bdeveloper|developed|studio\b", re.IGNORECASE)
STOPWORDS = {
    "a",
    "an",
    "and",
    "are",
    "for",
    "from",
    "in",
    "is",
    "it",
    "of",
    "on",
    "the",
    "to",
    "was",
    "what",
    "when",
    "which",
    "who",
}


class RetrievedGame(BaseModel):
    """Structured representation of a retrieved game document."""

    id: str
    score: float = Field(ge=0.0, le=1.0)
    content: str
    metadata: Dict[str, Any]


class RetrievalEvaluationReport(BaseModel):
    """Evaluation report that determines whether web fallback is required."""

    useful: bool
    confidence: float = Field(ge=0.0, le=1.0)
    use_web_search: bool
    description: str
    matched_games: List[str] = Field(default_factory=list)


class SourceCitation(BaseModel):
    """Citation metadata for the final answer."""

    source_type: str
    label: str
    locator: str


class ResearchAnswer(BaseModel):
    """Structured answer returned by the UdaPlay agent."""

    question: str
    answer: str
    confidence: float = Field(ge=0.0, le=1.0)
    route: str
    citations: List[SourceCitation] = Field(default_factory=list)
    supporting_data: Dict[str, Any] = Field(default_factory=dict)


@dataclass
class GameRecord:
    """Represents a single game record loaded from the local JSON dataset."""

    doc_id: str
    name: str
    platform: str
    genre: str
    publisher: str
    description: str
    year_of_release: int
    source_path: str

    @classmethod
    def from_file(cls, file_path: Path) -> "GameRecord":
        """Load a game record from a JSON file."""
        with file_path.open("r", encoding="utf-8") as handle:
            data = json.load(handle)
        return cls(
            doc_id=file_path.stem,
            name=data["Name"],
            platform=data["Platform"],
            genre=data["Genre"],
            publisher=data["Publisher"],
            description=data["Description"],
            year_of_release=int(data["YearOfRelease"]),
            source_path=str(file_path),
        )

    def to_document(self) -> Document:
        """Convert the record into a vector-store document."""
        return Document(
            id=self.doc_id,
            content=(
                f"Game: {self.name}\n"
                f"Platform: {self.platform}\n"
                f"Genre: {self.genre}\n"
                f"Publisher: {self.publisher}\n"
                f"Release Year: {self.year_of_release}\n"
                f"Description: {self.description}"
            ),
            metadata={
                "Name": self.name,
                "Platform": self.platform,
                "Genre": self.genre,
                "Publisher": self.publisher,
                "Description": self.description,
                "YearOfRelease": self.year_of_release,
                "source_path": self.source_path,
            },
        )


class UdaPlayServices:
    """Project-level services for dataset loading, retrieval, evaluation, and memory."""

    def __init__(
        self,
        games_directory: str,
        persist_directory: str,
        collection_name: str = "udaplay_games",
        memory_collection_name: str = "udaplay_research_memory",
        openai_api_key: Optional[str] = None,
        tavily_api_key: Optional[str] = None,
    ):
        """Initialize vector storage, optional web search, and long-term memory."""
        self.games_directory = Path(games_directory)
        self.persist_directory = Path(persist_directory)
        self.collection_name = collection_name
        self.vector_manager = VectorStoreManager(
            openai_api_key=openai_api_key,
            persist_directory=str(self.persist_directory),
        )
        self.vector_store = self.vector_manager.get_or_create_store(collection_name)
        self.long_term_memory = LongTermMemory(
            db=self.vector_manager,
            collection_name=memory_collection_name,
        )
        self.tavily_client = TavilyClient(api_key=tavily_api_key) if tavily_api_key else None

    def load_games(self) -> List[GameRecord]:
        """Load and validate all game JSON files from disk."""
        records: List[GameRecord] = []
        for file_path in sorted(self.games_directory.glob("*.json")):
            records.append(GameRecord.from_file(file_path))
        return records

    def index_games(self, force: bool = False) -> int:
        """Index the local game dataset into the persistent vector store."""
        if force:
            self.vector_manager.delete_store(self.collection_name)
            self.vector_store = self.vector_manager.get_or_create_store(self.collection_name)

        records = self.load_games()
        existing_ids = set(self.vector_store.get().get("ids", []))
        documents_to_add = [record.to_document() for record in records if record.doc_id not in existing_ids]
        if documents_to_add:
            self.vector_store.add(documents_to_add)
        return len(records)

    def retrieve_game(self, query: str, n_results: int = 5) -> Dict[str, Any]:
        """Run semantic retrieval against the local game vector store."""
        results = self.vector_store.query(query_texts=[query], n_results=n_results)
        documents = results.get("documents", [[]])[0]
        metadatas = results.get("metadatas", [[]])[0]
        distances = results.get("distances", [[]])[0]
        ids = results.get("ids", [[]])[0]

        retrieved = []
        for doc_id, content, metadata, distance in zip(ids, documents, metadatas, distances):
            score = 1.0 / (1.0 + float(distance))
            retrieved.append(
                RetrievedGame(
                    id=doc_id,
                    score=round(score, 4),
                    content=content,
                    metadata=metadata,
                ).model_dump()
            )

        return {
            "query": query,
            "results": retrieved,
            "result_count": len(retrieved),
        }

    def evaluate_retrieval(self, question: str, retrieved_docs: str) -> Dict[str, Any]:
        """Score retrieval usefulness and decide whether fallback search is required."""
        payload = json.loads(retrieved_docs) if isinstance(retrieved_docs, str) else retrieved_docs
        results = payload.get("results", [])
        if not results:
            report = RetrievalEvaluationReport(
                useful=False,
                confidence=0.0,
                use_web_search=True,
                description="No local documents were retrieved, so the answer needs web research.",
            )
            return report.model_dump()

        top_result = results[0]
        top_metadata = top_result.get("metadata", {})
        top_score = float(top_result.get("score", 0.0))
        combined_text = " ".join(
            str(value) for value in [top_result.get("content", ""), *top_metadata.values()]
        ).lower()

        question_tokens = {
            token
            for token in re.findall(r"[a-zA-Z0-9']+", question.lower())
            if token not in STOPWORDS and len(token) > 2
        }
        overlap = sorted(token for token in question_tokens if token in combined_text)
        overlap_ratio = len(overlap) / max(len(question_tokens), 1)

        unsupported_request = bool(DEVELOPER_PATTERN.search(question) or CURRENT_INFO_PATTERN.search(question))
        exact_name_match = top_metadata.get("Name", "").lower() in question.lower()
        supported_locally = not unsupported_request

        confidence = min(1.0, (top_score * 0.7) + (overlap_ratio * 0.3))
        useful = supported_locally and (top_score >= 0.45) and (overlap_ratio >= 0.2 or exact_name_match)
        use_web_search = not useful

        reason_parts = [
            f"Top local score: {top_score:.2f}",
            f"Question overlap ratio: {overlap_ratio:.2f}",
        ]
        if unsupported_request:
            reason_parts.append(
                "The question asks for current or developer-specific information that is not represented in the local dataset."
            )

        report = RetrievalEvaluationReport(
            useful=useful,
            confidence=round(confidence, 4),
            use_web_search=use_web_search,
            description=" ".join(reason_parts),
            matched_games=[result.get("metadata", {}).get("Name", "") for result in results if result.get("metadata")],
        )
        return report.model_dump()

    def search_research_memory(self, question: str, limit: int = 3) -> Dict[str, Any]:
        """Search long-term memory for prior web research relevant to the question."""
        search_result = self.long_term_memory.search(
            query_text=question,
            owner="udaplay",
            limit=limit,
            namespace="research",
        )
        memories = []
        for fragment, distance in zip(search_result.fragments, search_result.metadata.get("distances", [])):
            memories.append(
                {
                    "content": fragment.content,
                    "score": round(1.0 / (1.0 + float(distance)), 4),
                    "timestamp": fragment.timestamp,
                }
            )
        return {
            "question": question,
            "results": memories,
            "result_count": len(memories),
        }

    def game_web_search(self, question: str, max_results: int = 5) -> Dict[str, Any]:
        """Search the web with Tavily when local knowledge is not sufficient."""
        if not self.tavily_client:
            return {
                "question": question,
                "answer": "Tavily is not configured. Add TAVILY_API_KEY to enable web fallback.",
                "results": [],
                "result_count": 0,
            }

        response = self.tavily_client.search(
            query=question,
            topic="general",
            max_results=max_results,
            search_depth="advanced",
            include_answer=True,
            include_raw_content=False,
        )

        results = []
        for item in response.get("results", []):
            results.append(
                {
                    "title": item.get("title", "Untitled source"),
                    "url": item.get("url", ""),
                    "content": item.get("content", ""),
                }
            )

        return {
            "question": question,
            "answer": response.get("answer", ""),
            "results": results,
            "result_count": len(results),
        }

    def store_research_memory(self, question: str, answer: str, sources: str) -> Dict[str, Any]:
        """Persist useful web findings so the agent can reuse them later."""
        source_items = json.loads(sources) if isinstance(sources, str) else sources
        content = json.dumps(
            {
                "question": question,
                "answer": answer,
                "sources": source_items,
            },
            ensure_ascii=True,
        )
        self.long_term_memory.register(
            MemoryFragment(
                content=content,
                owner="udaplay",
                namespace="research",
            )
        )
        return {"stored": True, "source_count": len(source_items)}


def create_udaplay_tools(services: UdaPlayServices) -> List[Tool]:
    """Create the tool list used by the tool-calling agent."""

    @tool
    def retrieve_game(query: str, n_results: int = 5) -> Dict[str, Any]:
        """Search the local game vector database for documents relevant to the user's question."""
        return services.retrieve_game(query=query, n_results=n_results)

    @tool
    def evaluate_retrieval(question: str, retrieved_docs: str) -> Dict[str, Any]:
        """Evaluate whether retrieved local documents are sufficient to answer the user's question."""
        return services.evaluate_retrieval(question=question, retrieved_docs=retrieved_docs)

    @tool
    def search_research_memory(question: str, limit: int = 3) -> Dict[str, Any]:
        """Search long-term memory for prior researched answers before using web search again."""
        return services.search_research_memory(question=question, limit=limit)

    @tool
    def game_web_search(question: str, max_results: int = 5) -> Dict[str, Any]:
        """Search the public web for game-industry information when internal knowledge is insufficient."""
        return services.game_web_search(question=question, max_results=max_results)

    @tool
    def store_research_memory(question: str, answer: str, sources: str) -> Dict[str, Any]:
        """Persist externally researched findings in long-term memory for future questions."""
        return services.store_research_memory(question=question, answer=answer, sources=sources)

    return [
        retrieve_game,
        evaluate_retrieval,
        search_research_memory,
        game_web_search,
        store_research_memory,
    ]


def create_udaplay_agent(services: UdaPlayServices, model_name: str = "gpt-4o-mini") -> Agent:
    """Create the state-machine-backed UdaPlay agent with project-specific instructions."""
    instructions = """
You are UdaPlay, a game research assistant.

Follow this exact workflow for every user question:
1. Call retrieve_game.
2. Call evaluate_retrieval using the original question and the full JSON returned by retrieve_game.
3. If evaluate_retrieval says use_web_search is false, answer from local knowledge.
4. If evaluate_retrieval says use_web_search is true, call search_research_memory.
5. If memory results are not useful, call game_web_search.
6. If game_web_search returns useful findings, call store_research_memory.

Answer requirements:
- Be concise and factual.
- Mention whether the answer came from local data, memory, or web search.
- Include citations as a flat list at the end.
- If the local dataset does not directly support the requested field, say so and use web search.
- Return valid JSON with keys: answer, route, confidence, citations, supporting_data.
""".strip()
    return Agent(
        model_name=model_name,
        instructions=instructions,
        tools=create_udaplay_tools(services),
        temperature=0.0,
    )


def bootstrap_udaplay_services(
    project_root: str,
    collection_name: str = "udaplay_games",
    memory_collection_name: str = "udaplay_research_memory",
) -> UdaPlayServices:
    """Load environment variables and construct the default UdaPlay service container."""
    load_dotenv(Path(project_root) / ".env")
    openai_api_key = os.getenv("CHROMA_OPENAI_API_KEY") or os.getenv("OPENAI_API_KEY")
    tavily_api_key = os.getenv("TAVILY_API_KEY")
    games_directory = Path(project_root) / "starter" / "games"
    persist_directory = Path(project_root) / "starter" / "chromadb"
    return UdaPlayServices(
        games_directory=str(games_directory),
        persist_directory=str(persist_directory),
        collection_name=collection_name,
        memory_collection_name=memory_collection_name,
        openai_api_key=openai_api_key,
        tavily_api_key=tavily_api_key,
    )